graph TD
;
%% webservice.py
    subgraph Webservice
        A[Client] -->|POST /polygonArray| B[PolygonServer];
        B -->|Read Request Body| C[json.loads];
        C -->|Process polygonArray| D[DataHelper.process_polygon_array];
        D -->|Load Config| E[BaseServer.load_config];
        E -->|Return Response| F[Client];
        A -->|POST /buildingGeometry| G[BuildingServer];
        G -->|Read Request Body| H[json.loads];
        H -->|Process buildingGeometry| I[DataHelper.process_building_geometry];
        I -->|Load Config| J[BaseServer.load_config];
        J -->|Return Response| F;
        A -->|PUT /updateBuildings| K[UpdateBuildingServer];
        K -->|Read Request Body| L[json.loads];
        L -->|Update buildingGeometry| M[DataHelper.update_buildings_gdf];
        M -->|Load Config| N[BaseServer.load_config];
        N -->|Return Response| F;
    end

%% helper.py
    subgraph Helper
        A1[DataHelper] -->|process_polygon_array| B1[_save_project_info];
        B1 --> C1[Save Project Info];
        A1 -->|process_polygon_array| D1[polygon_creator.user_polygon];
        D1 --> E1[manager.run_scenarios];
        A1 -->|process_building_geometry| F1[_save_project_info];
        F1 --> G1[Save Project Info];
        A1 -->|process_building_geometry| H1[_load_building_geometry];
        H1 --> I1[_save_building_geometry];
        I1 --> J1[polygon_creator.create_polygon_from_buildings];
        J1 --> K1[manager.run_scenarios];
        A1 -->|update_buildings_gdf| L1[_save_project_info];
        L1 --> M1[Save Project Info];
        A1 -->|update_buildings_gdf| N1[_load_building_geometry];
        N1 --> O1[_save_building_geometry];
        O1 --> P1[polygon_creator.create_polygon_from_buildings];
        P1 --> Q1[manager.run_scenarios];
    end

%% scenario_manager.py
    subgraph ScenarioManager
        A2[ScenarioManager] -->|run_scenarios| B2[reload_config];
        B2 --> C2[get_project_info];
        A2 -->|run_scenarios| D2[prepare];
        D2 --> E2[PrepMain.run];
        A2 -->|run_scenarios| F2[Run Each Scenario];
        F2 -->|baseline| G2[BaselineScenario.run_scenario];
        F2 -->|geometry| H2[GeometryScenario.run_scenario];
        F2 -->|demographic| I2[DemographicScenario.run_scenario];
        F2 -->|energy| J2[EnergyScenario.run_scenario];
        A2 -->|run_scenarios| K2[save_building_file];
        K2 --> L2[Generate Output];
        L2 --> M2[OutputFileGenerator.generate_output_file];
        M2 --> N2[DBServerUploader.upload_geojson];
    end